import type { InsertSkill } from "@shared/schema";

// FIG 2025-2028 Code of Points Skills Data
// Based on Women's Artistic Gymnastics Code of Points

export const vaultSkills: InsertSkill[] = [
  // Group 1 - Handspring, Yamashita, Round-off
  { name: "Handspring forward", value: "Vault", event: "Vault", vaultValue: 1.6, skillGroup: null, description: "Group 1 basic vault" },
  { name: "Handspring forward - 1/2 turn off", value: "Vault", event: "Vault", vaultValue: 2.0, skillGroup: null, description: "Group 1" },
  { name: "Handspring forward - 1/1 turn off", value: "Vault", event: "Vault", vaultValue: 2.6, skillGroup: null, description: "Group 1" },
  { name: "Handspring forward - 1.5/1 turn off (Kim)", value: "Vault", event: "Vault", vaultValue: 3.2, skillGroup: null, description: "Group 1" },
  { name: "Handspring forward - 2/1 turn off", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 1" },
  { name: "Handspring forward - 2.5/1 turn off", value: "Vault", event: "Vault", vaultValue: 4.0, skillGroup: null, description: "Group 1" },
  { name: "Yamashita", value: "Vault", event: "Vault", vaultValue: 2.0, skillGroup: null, description: "Group 1" },
  { name: "Yamashita with 1/2 turn off", value: "Vault", event: "Vault", vaultValue: 2.4, skillGroup: null, description: "Group 1" },
  { name: "Yamashita with 1/1 turn off", value: "Vault", event: "Vault", vaultValue: 2.8, skillGroup: null, description: "Group 1" },
  { name: "Round-off", value: "Vault", event: "Vault", vaultValue: 1.6, skillGroup: null, description: "Group 1" },
  { name: "Round-off - 1/2 turn off", value: "Vault", event: "Vault", vaultValue: 2.0, skillGroup: null, description: "Group 1" },
  { name: "Round-off - 1/1 turn off", value: "Vault", event: "Vault", vaultValue: 2.6, skillGroup: null, description: "Group 1" },
  { name: "Handspring fwd 1/2 turn on - stretched fly off", value: "Vault", event: "Vault", vaultValue: 2.4, skillGroup: null, description: "Group 1" },
  { name: "Handspring fwd 1/2 turn on - 1/2 turn off", value: "Vault", event: "Vault", vaultValue: 2.8, skillGroup: null, description: "Group 1" },
  { name: "Handspring fwd 1/2 turn on - 1/1 turn off (Omelianchik)", value: "Vault", event: "Vault", vaultValue: 3.4, skillGroup: null, description: "Group 1" },
  { name: "Handspring fwd 1/1 turn on - 1/1 turn off", value: "Vault", event: "Vault", vaultValue: 3.8, skillGroup: null, description: "Group 1" },
  
  // Group 2 - Handspring forward with salto
  { name: "Handspring fwd on - tucked salto fwd off", value: "Vault", event: "Vault", vaultValue: 3.0, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - piked salto fwd off", value: "Vault", event: "Vault", vaultValue: 3.4, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - stretched salto fwd off", value: "Vault", event: "Vault", vaultValue: 4.0, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - tucked salto fwd with 1/2 twist off (Rulfova)", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - stretched salto fwd with 1/2 twist off", value: "Vault", event: "Vault", vaultValue: 4.4, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - stretched salto fwd with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 4.8, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd on - tucked double salto fwd off", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd 1/2 on - stretched salto bwd off (Cuervo)", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 2 Cuervo" },
  { name: "Handspring fwd 1/2 on - stretched salto bwd with 1/2 twist off", value: "Vault", event: "Vault", vaultValue: 4.0, skillGroup: null, description: "Group 2 Cuervo" },
  { name: "Handspring fwd 1/2 on - stretched salto bwd with 1/1 twist off (Podkopayeva)", value: "Vault", event: "Vault", vaultValue: 4.6, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd 1/2 on - stretched salto bwd with 1.5/1 twist off", value: "Vault", event: "Vault", vaultValue: 5.0, skillGroup: null, description: "Group 2" },
  { name: "Handspring fwd 1/2 on - stretched salto bwd with 2/1 twist off (Cheng)", value: "Vault", event: "Vault", vaultValue: 5.4, skillGroup: null, description: "Group 2 Cheng" },
  
  // Group 3 - Tsukahara
  { name: "Tsukahara tucked", value: "Vault", event: "Vault", vaultValue: 2.8, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara piked", value: "Vault", event: "Vault", vaultValue: 3.2, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara stretched", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara tucked with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara stretched with 1/1 twist off (Kasamatsu)", value: "Vault", event: "Vault", vaultValue: 4.4, skillGroup: null, description: "Group 3 Kasamatsu" },
  { name: "Tsukahara stretched with 1.5/1 twist off", value: "Vault", event: "Vault", vaultValue: 4.8, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara stretched with 2/1 twist off", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara stretched with 2.5/1 twist off", value: "Vault", event: "Vault", vaultValue: 5.6, skillGroup: null, description: "Group 3" },
  { name: "Tsukahara tucked double salto off", value: "Vault", event: "Vault", vaultValue: 5.6, skillGroup: null, description: "Group 3" },
  
  // Group 4 - Yurchenko
  { name: "Yurchenko tucked", value: "Vault", event: "Vault", vaultValue: 2.8, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko piked", value: "Vault", event: "Vault", vaultValue: 3.2, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko tucked with 1/2 twist off", value: "Vault", event: "Vault", vaultValue: 3.2, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko tucked with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched with 1/2 twist off", value: "Vault", event: "Vault", vaultValue: 4.0, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 4.4, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched with 1.5/1 twist off (Lopez)", value: "Vault", event: "Vault", vaultValue: 4.8, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched with 2/1 twist off (Amanar)", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 4 Amanar" },
  { name: "Yurchenko stretched with 2.5/1 twist off (Biles)", value: "Vault", event: "Vault", vaultValue: 5.6, skillGroup: null, description: "Group 4 Biles" },
  { name: "Yurchenko stretched with 3/1 twist off (Biles II)", value: "Vault", event: "Vault", vaultValue: 6.0, skillGroup: null, description: "Group 4 Biles II" },
  { name: "Yurchenko tucked double salto off", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko piked double salto off", value: "Vault", event: "Vault", vaultValue: 5.6, skillGroup: null, description: "Group 4" },
  { name: "Yurchenko stretched double salto off (Produnova)", value: "Vault", event: "Vault", vaultValue: 6.0, skillGroup: null, description: "Group 4 Produnova" },
  
  // Group 5 - Round-off 1/2 on
  { name: "Round-off 1/2 on - tucked salto fwd off", value: "Vault", event: "Vault", vaultValue: 3.4, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - piked salto fwd off", value: "Vault", event: "Vault", vaultValue: 3.8, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto fwd off (Khorkina)", value: "Vault", event: "Vault", vaultValue: 4.4, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto fwd with 1/2 twist off", value: "Vault", event: "Vault", vaultValue: 4.8, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto fwd with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - tucked double salto fwd off", value: "Vault", event: "Vault", vaultValue: 5.4, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto bwd off", value: "Vault", event: "Vault", vaultValue: 3.6, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto bwd with 1/1 twist off", value: "Vault", event: "Vault", vaultValue: 4.4, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto bwd with 1.5/1 twist off", value: "Vault", event: "Vault", vaultValue: 4.8, skillGroup: null, description: "Group 5" },
  { name: "Round-off 1/2 on - stretched salto bwd with 2/1 twist off", value: "Vault", event: "Vault", vaultValue: 5.2, skillGroup: null, description: "Group 5" },
];

export const barsSkills: InsertSkill[] = [
  // Mounts (Group 1)
  { name: "Glide kip", value: "A", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to hang on HB", value: "A", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to glide kip on LB", value: "A", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump with 1/2 turn to hang on HB", value: "A", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to hstd on LB with hips bent", value: "B", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to hstd on LB with 1/2 turn in hstd", value: "B", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump with extended body to hstd on LB", value: "C", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to hstd on LB with 1/1 turn in hstd", value: "C", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump with extended body to hstd on LB with 1/1 turn (Maaranen)", value: "D", event: "Bars", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to clear support on HB - clear hip circle to hstd (McNamara)", value: "D", event: "Bars", skillGroup: "Mounts", crTags: [] },
  
  // Cast/Handstand (Group 2)
  { name: "Cast to hstd with legs straddled", value: "A", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Cast to hstd with legs together", value: "B", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Cast with 1/2 turn to hstd", value: "B", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Cast with 1/1 turn to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Cast with 1.5/1 turn to hstd (Reeder)", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Clear hip circle to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Clear hip circle with 1/2 turn to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Clear hip circle with 1/1 turn to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Clear hip circle with 1.5/1 turn to hstd", value: "E", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Clear hip circle fwd to hstd (Weiler-kip)", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Clear hip circle fwd with 1/1 turn to hstd (Godwin)", value: "E", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Hip circle backward", value: "A", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Hip circle forward", value: "A", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  
  // Giant Circles/Release Moves (Group 3)
  { name: "Giant circle backward", value: "B", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips"] },
  { name: "Giant circle backward with 1/2 turn to hstd", value: "B", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips"] },
  { name: "Giant circle backward with 1/1 turn to hstd", value: "C", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips", "non_flight_360_turn"] },
  { name: "Giant circle backward with 1.5/1 turn to hstd", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips", "non_flight_360_turn"] },
  { name: "Giant circle backward with 2/1 turn to hstd (Chusovitina)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips", "non_flight_360_turn"] },
  { name: "Giant circle forward", value: "B", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips"] },
  { name: "Giant circle forward with 1/2 turn to hstd", value: "B", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips"] },
  { name: "Giant circle forward with 1/1 turn to hstd", value: "C", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips", "non_flight_360_turn"] },
  { name: "Giant circle forward with 1.5/1 turn to hstd", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["different_grips", "non_flight_360_turn"] },
  { name: "Tkatchev straddled (Davydova)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Tkatchev piked", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Tkatchev with 1/2 turn (Kononenko)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Tkatchev with 1/2-1/2 turn (Shushunova)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Jaeger salto tucked", value: "C", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Jaeger salto straddled", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Jaeger salto piked", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Jaeger salto stretched (Capuccitti)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Jaeger salto stretched with 1/1 turn (Yang)", value: "F", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Gienger salto", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Deltchev salto straddled (Moreno/Nakamura)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Pak salto", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Pak salto with 1/1 turn (Bhardwaj)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Shaposhnikova", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Shaposhnikova with 1/2 turn (Khorkina)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Hindorff (counter straddle over HB)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Clear hip circle counter pike over HB (Shang)", value: "F", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Stalder circle backward to hstd", value: "C", event: "Bars", skillGroup: "Release Moves", crTags: [] },
  { name: "Stalder circle with 1/1 turn to hstd (Kim)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["non_flight_360_turn"] },
  { name: "Stalder circle to Tkatchev (Tweddle)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Stalder to Shaposhnikova (Chow)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Toe-on circle to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Toe-on circle with 1/1 turn to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: ["non_flight_360_turn"] },
  { name: "Toe-on to Pak salto (He Kexin)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  
  // Dismounts (Group 6)
  { name: "Flyaway tucked", value: "A", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched", value: "B", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched with 1/1 twist", value: "C", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched with 1.5/1 twist", value: "C", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched with 2/1 twist", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched with 2.5/1 twist", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Flyaway stretched with 3/1 twist", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward tucked", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward piked", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward stretched", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward tucked with 1/1 twist", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward stretched with 1/1 twist", value: "F", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto backward stretched with 2/1 twist (Mustafina)", value: "G", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto forward tucked", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double salto forward piked", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Salto fwd stretched with 1/1 twist", value: "C", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Salto fwd stretched with 2/1 twist", value: "D", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  
  // Additional Bars Skills (FIG 2025-2028)
  { name: "Kip to handstand", value: "B", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Stalder backward with 1/2 turn to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Stalder forward to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Toe-on circle backward with 1/2 turn to hstd", value: "C", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Toe-on circle forward to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Inbar stalder to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Inbar toe-on to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Endo circle to hstd", value: "D", event: "Bars", skillGroup: "Cast/Handstand", crTags: [] },
  { name: "Tkatchev stretched (Ezhova)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Ray (straddled Jaeger with 1/2 turn)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Piked Tkatchev (Hindorff piked)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Shaposhnikova with 1/1 turn (Maloney)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Counter Kim (toe-on Tkatchev)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Church (pike sole circle counter pike reverse hecht)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Komova (Stalder Shaposhnikova with 1/2 turn)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Nabieva (piked Tkatchev with 1/2 turn)", value: "F", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Downie (Shaposhnikova with 1/2 pike)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Van Leeuwen (Tkatchev straddled with 1/1 turn)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Derwael-Fenton (piked Nabieva)", value: "G", event: "Bars", skillGroup: "Release Moves", crTags: ["same_bar_flight"] },
  { name: "Ricna (toe-on Shaposhnikova)", value: "E", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Def (counter Pak salto)", value: "D", event: "Bars", skillGroup: "Release Moves", crTags: ["hb_to_lb_flight"] },
  { name: "Double salto backward tucked with 1/2 twist", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Double front tucked with 1/2 twist", value: "E", event: "Bars", skillGroup: "Dismounts", crTags: [] },
  { name: "Triple back tucked (Biles)", value: "H", event: "Bars", skillGroup: "Dismounts", crTags: [] },
];

export const beamSkills: InsertSkill[] = [
  // Mounts (Group 1)
  { name: "Jump to squat on beam", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to straddle on beam", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to front support", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Jump with 1/2 turn to squat on beam", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Squat on - jump to stand", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Straddle mount", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Wolf mount", value: "A", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Press to handstand mount", value: "B", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Jump to cross handstand mount", value: "B", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Handspring mount", value: "B", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Round-off mount", value: "B", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Aerial cartwheel mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: ["acro_directions"] },
  { name: "Aerial walkover mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Front salto tucked mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: ["acro_directions"] },
  { name: "Front salto piked mount", value: "D", event: "Beam", skillGroup: "Mounts", crTags: ["acro_directions"] },
  { name: "Front salto stretched mount", value: "D", event: "Beam", skillGroup: "Mounts", crTags: ["acro_directions"] },
  { name: "Back salto tucked mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Back salto stretched mount", value: "D", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Back salto stretched with 1/1 twist mount", value: "E", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Round-off flic-flac mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Round-off back salto stretched mount", value: "D", event: "Beam", skillGroup: "Mounts", crTags: [] },
  
  // Dance/Leaps (Group 2)
  { name: "Straight jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Split jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Split leap", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Straddle jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Tuck jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Cat leap", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Sissone", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Split jump with 1/2 turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Split leap with 1/2 turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Switch leap", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Switch leap with 1/2 turn", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Switch leap with 1/1 turn", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Split jump with 1/1 turn", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Sheep jump", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Ring leap", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Switch ring leap", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Wolf jump with 1/1 turn", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf jump with 2/1 turn", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Side split leap", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Tour jete (split leap with 1/2 turn)", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Johnson leap (switch side leap)", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Pike jump", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  
  // Turns (Group 3)
  { name: "1/1 turn (360°)", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "1.5/1 turn (540°)", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "2/1 turn (720°)", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "2.5/1 turn (900°)", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "3/1 turn (1080°)", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "L-turn 1/1 (360°)", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "L-turn 2/1 (720°)", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Y-turn 1/1 (360°)", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Y-turn 2/1 (720°)", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Illusion turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Back attitude turn 1/1 (360°)", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  
  // Acrobatic (Group 4-5)
  { name: "Cartwheel", value: "A", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions"] },
  { name: "Handstand", value: "A", event: "Beam", skillGroup: "Acrobatic", crTags: [] },
  { name: "Forward walkover", value: "A", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions"] },
  { name: "Backward walkover", value: "A", event: "Beam", skillGroup: "Acrobatic", crTags: [] },
  { name: "Back handspring step-out", value: "B", event: "Beam", skillGroup: "Acrobatic", crTags: [] },
  { name: "Back handspring", value: "B", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Flic-flac (back handspring)", value: "B", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Front handspring", value: "B", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Flic-flac with 1/1 turn", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Front aerial", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Side aerial", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Back aerial (Flic without hands)", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto tucked", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto piked", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto stretched", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto stretched with 1/2 twist", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto stretched with 1/1 twist", value: "E", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto stretched with 2/1 twist", value: "F", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Front salto tucked", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Front salto piked", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Front salto stretched", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Gainer salto tucked", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Gainer salto stretched", value: "E", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back layout step-out (Onodi prep)", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Onodi (Flic 1/2 to front layout)", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Standing back tuck", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  
  // Dismounts (Group 6)
  { name: "Cartwheel to side handstand 1/4 turn dismount", value: "A", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Round-off dismount", value: "A", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto tucked dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched with 1/1 twist dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched with 1.5/1 twist dismount", value: "D", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched with 2/1 twist dismount", value: "D", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched with 2.5/1 twist dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back salto stretched with 3/1 twist dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back tucked dismount", value: "D", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back piked dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back stretched dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back tucked with 1/1 twist dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back stretched with 1/1 twist dismount (Mustafina)", value: "G", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Gainer back salto stretched dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Gainer with 1/1 twist dismount", value: "D", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Gainer with 2/1 twist dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Side aerial dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Front salto tucked dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Front salto stretched dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Front salto stretched with 1/2 twist dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Front salto stretched with 1/1 twist dismount", value: "D", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double front tucked dismount", value: "E", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Arabian double front tucked dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  
  // Additional Beam Skills (FIG 2025-2028)
  // More Dance/Leaps
  { name: "Stag leap", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Stag ring leap", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Double stag leap", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Split leap with leg change", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Split leap with ring position", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Wolf jump with 3/1 turn", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Split leap with 3/4 turn", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Switch leap ring", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Cross split leap", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Stretched jump with 1/1 turn", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Stretched jump with 2/1 turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Sheep jump with 1/2 turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Cat leap with 1/2 turn", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Cat leap with 1/1 turn", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Popa (switch leap 1/4 turn to cross split)", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  { name: "Kochetkova (switch leap 1/4 to ring)", value: "E", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["dance_connection"] },
  
  // More Turns
  { name: "3.5/1 turn (1260°)", value: "F", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "4/1 turn (1440°)", value: "F", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "L-turn 1.5/1 (540°)", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Y-turn 1.5/1 (540°)", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Illusion turn 2/1", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Fouette turn 1/1", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Fouette turn 2/1", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Wolf turn 1/1", value: "B", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Wolf turn 2/1", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Wolf turn 3/1", value: "D", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Tuck turn 1/1", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Tuck turn 2/1", value: "C", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Backward roll", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  { name: "Forward roll", value: "A", event: "Beam", skillGroup: "Dance/Leaps", crTags: ["turn_or_roll"] },
  
  // More Acrobatic
  { name: "Round-off", value: "A", event: "Beam", skillGroup: "Acrobatic", crTags: [] },
  { name: "Flic-flac series (2 flic-flacs)", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Flic-flac to 2 feet", value: "B", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Gainer flic-flac", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto tucked step-out", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back salto piked step-out", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Back 2.25 salto to cross sit (Thomas)", value: "F", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Front tuck connected to back handspring", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Barani (front salto with 1/2 twist)", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Whip back (tempo salto)", value: "C", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  { name: "Side salto tucked", value: "D", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Side salto stretched", value: "E", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_directions", "acro_series"] },
  { name: "Patterson (back salto layout with 1/2 twist step-out)", value: "E", event: "Beam", skillGroup: "Acrobatic", crTags: ["acro_series"] },
  
  // More Mounts
  { name: "Flip-flac mount from end of beam", value: "B", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Double back tucked mount (from springboard)", value: "E", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Full-twisting back mount", value: "D", event: "Beam", skillGroup: "Mounts", crTags: [] },
  { name: "Yurchenko mount", value: "C", event: "Beam", skillGroup: "Mounts", crTags: [] },
  
  // More Dismounts
  { name: "Gainer double back tucked dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Gainer with 3/1 twist dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Triple twist dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Double back stretched with 2/1 twist dismount (Biles)", value: "H", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Front double tucked with 1/2 twist dismount", value: "F", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Side aerial with 1/4 turn dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Back handspring full twist dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Arabian salto dismount", value: "C", event: "Beam", skillGroup: "Dismounts", crTags: [] },
  { name: "Punch front salto tucked dismount", value: "B", event: "Beam", skillGroup: "Dismounts", crTags: [] },
];

export const floorSkills: InsertSkill[] = [
  // Dance/Leaps (Group 1)
  { name: "Straight jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Split jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Straddle jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Tuck jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Cat leap", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Sissone", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Split jump with 1/2 turn", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap with 1/2 turn", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split jump with 1/1 turn", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap with 1/1 turn", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap with 2/1 turn", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Switch leap", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Switch leap with 1/2 turn", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Switch leap with 1/1 turn", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Ring leap", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Switch ring leap", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Sheep jump", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf jump with 1/1 turn", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf jump with 2/1 turn", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Straddle pike jump with 1/2 turn", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Straddle pike jump with 1/1 turn", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Tour jete (split leap with 1/2 turn)", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Tour jete with 1/1 turn", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Johnson leap (switch side leap)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Side split leap", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Pike jump", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  
  // Turns (Group 2)
  { name: "1/1 turn (360°)", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "2/1 turn (720°)", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "3/1 turn (1080°)", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "4/1 turn (1440°)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "L-turn 1/1 (360°)", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "L-turn 2/1 (720°)", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Y-turn 1/1 (360°)", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Y-turn 2/1 (720°)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Illusion turn", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Back attitude turn 1/1 (360°)", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf turn 2/1", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf turn 3/1", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf turn 4/1", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  
  // Forward Tumbling (Group 3-4)
  { name: "Forward roll", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: [] },
  { name: "Handstand forward roll", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: [] },
  { name: "Front walkover", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: [] },
  { name: "Front handspring", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: [] },
  { name: "Front aerial", value: "B", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Front salto tucked", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Front salto piked", value: "B", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Front salto stretched", value: "C", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Front salto stretched with 1/2 twist", value: "C", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Front salto stretched with 1/1 twist", value: "D", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Front salto stretched with 1.5/1 twist", value: "D", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Front salto stretched with 2/1 twist", value: "E", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Double front tucked", value: "D", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Double front piked", value: "E", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Double front stretched", value: "F", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Arabian double front tucked", value: "E", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Arabian double front piked", value: "F", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Punch front tucked", value: "A", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Punch front piked", value: "B", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Punch front stretched", value: "C", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  
  // Backward Tumbling (Group 5)
  { name: "Backward roll", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Backward roll to handstand", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Back walkover", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Round-off", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Flic-flac (back handspring)", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Back salto tucked", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Back salto piked", value: "B", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Back salto stretched", value: "B", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Back salto stretched with 1/1 twist", value: "B", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Back salto stretched with 1.5/1 twist", value: "C", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Back salto stretched with 2/1 twist (full-in)", value: "C", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Back salto stretched with 2.5/1 twist", value: "D", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Back salto stretched with 3/1 twist", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Back salto stretched with 3.5/1 twist", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Double back tucked", value: "C", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Double back piked", value: "D", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Double back stretched", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Double back tucked with 1/1 twist (full-in)", value: "D", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back piked with 1/1 twist (full-in piked)", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back tucked with 2/1 twist (double-full)", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back stretched with 1/1 twist", value: "F", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back stretched with 2/1 twist (Silivas)", value: "G", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Triple back tucked", value: "G", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Triple back piked (Biles)", value: "H", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Whip back (tempo back)", value: "A", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  
  // Dismounts (last acro element)
  { name: "Back 1.5 tucked (dismount connection)", value: "B", event: "Floor", skillGroup: "Dismounts", crTags: [] },
  { name: "Back 1.5 stretched (dismount connection)", value: "C", event: "Floor", skillGroup: "Dismounts", crTags: [] },
  { name: "Back 1.5 stretched with 1/1 twist", value: "D", event: "Floor", skillGroup: "Dismounts", crTags: ["salto_la_turn"] },
  { name: "Back 1.5 stretched with 2/1 twist (Rudi out)", value: "E", event: "Floor", skillGroup: "Dismounts", crTags: ["salto_la_turn"] },
  
  // Additional Floor Skills (FIG 2025-2028)
  // More Dance/Leaps
  { name: "Stag leap", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Stag ring leap", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Double stag leap", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap with leg change", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Split leap with 1.5/1 turn", value: "C", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Popa (switch leap 1/4 turn to cross split)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Kochetkova (switch leap 1/4 to ring)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Onodi leap (switch leap 1/4 with 1/2 turn)", value: "E", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Switch half with ring", value: "E", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Cross split leap", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: ["dance_passage"] },
  { name: "Fouette hop", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  
  // More Turns  
  { name: "5/1 turn (1800°)", value: "E", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "6/1 turn (2160°)", value: "F", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "L-turn 3/1 (1080°)", value: "D", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Y-turn 3/1 (1080°)", value: "E", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Illusion turn 2/1", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Fouette turn 1/1", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Fouette turn 2/1", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Tuck turn 1/1", value: "A", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Tuck turn 2/1", value: "B", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf turn 5/1", value: "E", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  { name: "Wolf turn 6/1", value: "F", event: "Floor", skillGroup: "Dance/Leaps", crTags: [] },
  
  // More Forward Tumbling
  { name: "Front salto stretched with 2.5/1 twist", value: "F", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Front salto stretched with 3/1 twist", value: "F", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  { name: "Double front with 1/2 twist out", value: "E", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Double front with 1/1 twist out", value: "F", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Triple front tucked", value: "G", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_double_ba"] },
  { name: "Barani (front salto with 1/2 twist)", value: "B", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd"] },
  { name: "Randy (front 2.5 twist)", value: "D", event: "Floor", skillGroup: "Forward Tumbling", crTags: ["salto_bwd_fwd", "salto_la_turn"] },
  
  // More Backward Tumbling
  { name: "Back salto stretched with 4/1 twist", value: "F", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Double back tucked with 1.5/1 twist", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back tucked with 2.5/1 twist", value: "F", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back tucked with 3/1 twist", value: "G", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back stretched with 3/1 twist", value: "H", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Double back piked with 2/1 twist", value: "F", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Full-in back-out tucked", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Full-in full-out tucked", value: "F", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Half-in half-out tucked", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Double layout with 1.5/1 twist (Moors)", value: "G", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Triple double (double-double-back tucked with 1/1 twist)", value: "I", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Biles II (triple double)", value: "J", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba", "salto_la_turn"] },
  { name: "Back 2.5 tucked", value: "D", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Back 2.5 stretched", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_double_ba"] },
  { name: "Gainer back tucked", value: "B", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Gainer back stretched", value: "C", event: "Floor", skillGroup: "Backward Tumbling", crTags: [] },
  { name: "Gainer with 1/1 twist", value: "D", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
  { name: "Gainer with 2/1 twist", value: "E", event: "Floor", skillGroup: "Backward Tumbling", crTags: ["salto_la_turn"] },
];

export const allSkills = [
  ...vaultSkills,
  ...barsSkills,
  ...beamSkills,
  ...floorSkills,
];
